# Generated by Django 3.0.6 on 2020-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='StatesImages/%Y/%m/%d')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
    ]
