# Generated by Django 3.0.6 on 2020-05-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='state_object',
            new_name='state_id',
        ),
    ]
