# Generated by Django 3.0.6 on 2020-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0002_auto_20200528_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('headlineId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('headlineText', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('addedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
    ]
