# Generated by Django 3.0.6 on 2020-05-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0003_auto_20200528_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='stateList',
            field=models.ManyToManyField(null=True, to='news_api_app.State'),
        ),
    ]
