# Generated by Django 3.0.6 on 2020-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0005_auto_20200528_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headlineId',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='stateId',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
