# Generated by Django 3.0.6 on 2020-05-28 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0006_auto_20200528_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headlineId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='stateId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
