# Generated by Django 3.0.6 on 2020-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0007_auto_20200528_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headlineId',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='stateId',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
