# Generated by Django 3.0.6 on 2020-05-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0008_auto_20200528_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='stateList',
        ),
    ]
