# Generated by Django 3.0.6 on 2020-05-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0010_auto_20200528_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'verbose_name_plural': 'Headlines'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.CreateModel(
            name='Companines',
            fields=[
                ('companyId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('companyUrl', models.CharField(max_length=250)),
                ('imageUlr', models.ImageField(blank=True, null=True, upload_to='CompaniesLogos/%Y/%m/%d')),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('addedOn', models.DateTimeField(auto_now=True)),
                ('stateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api_app.State')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
