# Generated by Django 3.0.6 on 2020-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0011_auto_20200529_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companines',
            name='companyUrl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companines',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
