# Generated by Django 3.0.6 on 2020-05-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0012_auto_20200529_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='companines',
            name='pdfUlr',
            field=models.FileField(null=True, upload_to='CompanyPDFs/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='companines',
            name='imageUlr',
            field=models.ImageField(blank=True, null=True, upload_to='CompaniesImages/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=50)),
                ('fileName', models.FileField(upload_to='CityPDFs/%Y/%m/%d')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='CompaniesImages/%Y/%m/%d')),
                ('newsDate', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
                ('addedOn', models.DateTimeField(auto_now=True)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api_app.Companines')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
