# Generated by Django 3.0.6 on 2020-05-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0013_auto_20200529_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='news_api_app.Companines'),
        ),
    ]
