# Generated by Django 3.0.6 on 2020-05-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0014_auto_20200529_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='companyName',
            new_name='companyId',
        ),
    ]
