# Generated by Django 3.0.6 on 2020-05-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0015_auto_20200529_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='companyId',
        ),
        migrations.AddField(
            model_name='cities',
            name='companyName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_api_app.Companines'),
        ),
    ]
