# Generated by Django 3.0.6 on 2020-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0016_auto_20200529_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='companines',
            name='newsDate',
            field=models.DateField(null=True),
        ),
    ]
