# Generated by Django 3.0.6 on 2020-05-29 08:32

from django.db import migrations, models
import news_api_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0017_companines_newsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='newsDate',
            field=models.CharField(max_length=20, null=True, validators=[news_api_app.models.date_validate]),
        ),
        migrations.AlterField(
            model_name='companines',
            name='newsDate',
            field=models.CharField(max_length=20, null=True, validators=[news_api_app.models.date_validate]),
        ),
    ]
