# Generated by Django 3.0.6 on 2020-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0018_auto_20200529_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineCategory',
            fields=[
                ('categoryId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
                ('imageUlr', models.ImageField(blank=True, null=True, upload_to='MagazineCategoryImages/%Y/%m/%d')),
                ('isActive', models.BooleanField(default=False)),
                ('addedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MagazineCategories',
            },
        ),
    ]
