# Generated by Django 3.0.6 on 2020-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0021_sundaymagazine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sundaymagazine',
            options={'verbose_name_plural': 'SundayMagazines'},
        ),
        migrations.AlterField(
            model_name='cities',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companines',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='magazinecategory',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sundaymagazine',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
