# Generated by Django 3.0.6 on 2020-06-01 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0022_auto_20200531_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('districtName', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('stateName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_api_app.State')),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
    ]
