# Generated by Django 3.0.6 on 2020-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0023_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='companines',
            name='districtName',
            field=models.TextField(null=True),
        ),
    ]
