# Generated by Django 3.0.6 on 2020-06-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0024_companines_districtname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companines',
            name='districtName',
        ),
        migrations.AddField(
            model_name='companines',
            name='districtNames',
            field=models.ManyToManyField(to='news_api_app.District'),
        ),
    ]
