# Generated by Django 3.0.6 on 2020-06-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0026_auto_20200601_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='addedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
