# Generated by Django 3.0.6 on 2020-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0028_auto_20200604_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='categoryName',
        ),
        migrations.AddField(
            model_name='magazine',
            name='categoryName',
            field=models.ManyToManyField(to='news_api_app.MagazineCategory'),
        ),
    ]
