# Generated by Django 3.0.6 on 2020-06-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0029_auto_20200604_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='imageUrl',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
