# Generated by Django 3.0.6 on 2020-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0031_auto_20200606_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companines',
            name='companyLogo',
        ),
        migrations.AlterField(
            model_name='companines',
            name='imageUlr',
            field=models.ImageField(blank=True, null=True, upload_to='CompaniesImages/%Y/%m/%d'),
        ),
    ]
