# Generated by Django 3.0.6 on 2020-06-06 16:29

from django.db import migrations, models
import django.db.models.deletion
import news_api_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0032_auto_20200606_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companines',
            name='newsDate',
        ),
        migrations.RemoveField(
            model_name='companines',
            name='pdfUlr',
        ),
        migrations.CreateModel(
            name='CompaninesPdf',
            fields=[
                ('companyPdfId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('pdfUlr', models.FileField(blank=True, null=True, upload_to='CompanyPDFs/%Y/%m/%d')),
                ('imageUlr', models.CharField(max_length=500, null=True)),
                ('newsDate', models.CharField(blank=True, max_length=20, null=True, validators=[news_api_app.models.date_validate])),
                ('isActive', models.BooleanField(default=False)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_api_app.Companines')),
                ('districtNames', models.ManyToManyField(to='news_api_app.District')),
            ],
            options={
                'verbose_name_plural': 'CompaninesPdfs',
            },
        ),
    ]
