# Generated by Django 3.0.6 on 2020-06-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0033_auto_20200606_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companinespdf',
            name='districtNames',
        ),
    ]
