# Generated by Django 3.0.6 on 2020-06-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0035_auto_20200608_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='CityPDFs/%Y/%m/%d'),
        ),
    ]
