# Generated by Django 3.0.6 on 2020-06-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0037_auto_20200609_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companinespdf',
            old_name='companyPdfId',
            new_name='companypdfId',
        ),
    ]
