# Generated by Django 3.0.6 on 2020-06-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0038_auto_20200609_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sundaymagazine',
            old_name='magazineId',
            new_name='id',
        ),
        migrations.AddField(
            model_name='sundaymagazine',
            name='imageName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companinespdf',
            name='imageUlr',
            field=models.ImageField(null=True, upload_to='CompanyNewsImages'),
        ),
    ]
